spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/external/users/**
            - id: mess-service-websocket
              uri: lb:ws://mess-service
              predicates:
                - Path=/ws/messages

server:
  port: ${API_GATEWAY_PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${API_GATEWAY_JWT_SECRET:local-dev-secret-key-for-user-service-jwt-256-bit}
