spring:
  application:
    name: mess-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}

server:
  port: ${MESS_SERVICE_PORT:0}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${HOSTNAME}

messaging:
  replica-id: ${eureka.instance.instance-id}
  websocket:
    endpoint: /ws/messages
  connection-service-url: ${CONNECTION_SERVICE_URL:http://connection-service}
  user-service-url: ${USER_SERVICE_URL:http://user-service}
  rabbit:
    presence-exchange: mess.presence
    presence-routing-key: presence.changed
    history-exchange: mess.history
    history-routing-key: message.store
    delivery-exchange: mess.delivery
    delivery-queue-prefix: mess.delivery.

logging:
  level:
    ru.privalov: debug
